name: 自动部署

on: 
  push:
    branches: 
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检查分支
        uses: actions/checkout@v2
        with:
          ref: main
      
      - name: 安装 Node
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      - name: 安装 Hexo
        run: |
          export TZ='Asia/Shanghai'
          npm install hexo-cli -g 

      - name: 安装依赖
        run: |
         npm install --save

      - name: 生成静态文件
        run: |
          npm run clean
          npm run build

      - name: 部署
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./public
