name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 下载代码
        uses: actions/checkout@v4
        
      - name: 设置 Node.js 环境
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 18
      - name: 安装依赖
        run: |
            npm install
            npm run build
      - name: 部署
        uses: actions/upload-pages-artifact@v3
        with:
          path: public