name: Sync Gitee

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps: 
      - name: sync-gitee-mirror
        uses: abersheeran/sync-gitee-mirror@v1-beta
        with:
          repository: uanfumin/blog
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
